apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: focus
  labels:
    app: focus
data:
  # Database config
  database_name: 'focus_prod'
  database_pool_min: '2'
  database_pool_max: '10'

  # Auth config
  jwt_expires_in: '30d'

  # CORS config
  cors_origin: 'https://focus-app.ru,http://focus-app.ru'
